### ISSUE TITLE
apple m1 chip base on arm arch runtime error

### ISSUE THREAD

**Issue by leotody** [volcengine/SecureUnionID#30]
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/cw/wzm0tktn7w74_bdmqd62w69w0000gp/T/libsecureunionidjni7765529474779975093.dylib: dlopen(/private/var/folders/cw/wzm0tktn7w74_bdmqd62w69w0000gp/T/libsecureunionidjni7765529474779975093.dylib, 0x0001): tried: '/private/var/folders/cw/wzm0tktn7w74_bdmqd62w69w0000gp/T/libsecureunionidjni7765529474779975093.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/lib/libsecureunionidjni7765529474779975093.dylib' (no such file)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
	at java.lang.Runtime.load0(Runtime.java:810)
	at java.lang.System.load(System.java:1086)
	at com.volcengine.secureunionid.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:79)
	at com.volcengine.secureunionid.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:57)
	at com.volcengine.secureunionid.SecureUnionID.loadLibrary(SecureUnionID.java:73)
	at com.volcengine.secureunionid.SecureUnionID.<clinit>(SecureUnionID.java:53)
	at com.volcengine.secureunionid.Demo.main(Demo.java:45)

**Comment by cqwei1** [comment]
The problem seems because " but is an incompatible architecture (have 'arm64', need 'x86_64')"?
So, please try to compile with the same platform with the running environment?
